# hun-diceware-word-list

* Hungarian DiceWare word list
** Design goals
*** Easy to remember.
Words used in classical literature books are extracted. These are the
books that every Hungarian probably have read. Words that are used
more frequent are considered easier to remember.
*** Easy to type
Only words with no accent are selected. These are easier to type even
on a foreign keyboard. (Probably the letters y and z should be
excluded too. But there are not enough confirming words for that.)
*** Use short words if possible
Short words are easier to remember and type.
*** The words should not be names or abbreviations.
Some of the names and abbreviations are cryptic and hard to remember.
** Method
*** Candidate words are extracted from a Hungarian spelling dictionary
The latest Hungarian spelling dictionary used by LibreOffice is
downloaded:
https://raw.githubusercontent.com/LibreOffice/dictionaries/master/hu_HU/hu_HU.dic
*** The candidate extracted words are filtered 
The candidate words will contain only words confirming to the [[*Design goals][Design
goals]].

*** Supporting words are extracted from the classical books. 
The supporting words must also confirm to the [[*Design goals][Design goals]].  Only
unique words are added to the candidate list.
*** Candidate words are filtered using the words in the supporting word list 
If a candidate word is found amongst the supporting words the word is
confirmed and used in final word list.
*** Candidate words which are one or two characters long are removed from the candidate list.
These short words usually come from Latin quotations or
Acronyms. These may not have meaning which makes them harder to
remember.
*** Candidate words are cut down to 7776 words
Candidate words are ordered by length and the first 7776 word is
selected.
*** Candidate words are exported to a text file.
Words are prefixed with the 6 digit number.
